apiVersion: v1
kind: Service
metadata: 
  name: client-cluster-ip-service
spec: 
  type: ClusterIP
  selector:
    component: web
  ports:
    - port: 3000 #PORT THAT WE ACCESS 
      targetPort: 3000 #PORT INSIDE THE POD TO ACCESS

